### ISSUE TITLE
[Request] Circle thicknes

### ISSUE THREAD

**Issue by mistersister** [RaidcoreGG/GW2-RangeIndicators#1]
As the title says:

Can we have an option to increase the thickness of the circles drawn? I use this addon with very small range indicators as way to locate my character amidst all the pools, flames, explosions and flashy spells covering the ground.

However, the circles are way too thin and not really that apparent. If we could have a setting to change the thickness, that would make it ideal.

Thanks.

**Comment by DeltaRaidcore** [comment]
Has been implemented as of yesterdays update!
